url: "http://27.148.193.68:9089/api/TokenAuth/Authenticate"
headers:
    Content-Type: "application/json-patch+json"
payload:
    usernameOrEmailAddress: 'dev_admin'
    password: '123qwe'

# Database interface
database_server: 'localhost'
database_name: 'ZEE600Data_Ins_SKDS'
username: 'ZEE600'
password: 'Aa123456'
